name: Build Docker Container

on:
    push:
        branches:
            - production
    
jobs:
    build-backend:
        runs-on: ubuntu-latest
        steps:
        -
            name: Checkout
            uses: actions/checkout@v4
        -
            name: Set up QEMU
            uses: docker/setup-qemu-action@v3
        -
            name: Set up Docker Buildx
            uses: docker/setup-buildx-action@v3
        -
            name: Login to Docker Hub
            uses: docker/login-action@v3
            with:
                username: ${{ secrets.DOCKERHUB_USERNAME }}
                password: ${{ secrets.DOCKERHUB_TOKEN }}
        - 
            name: Log in to the Container registry
            uses: docker/login-action@v3
            with:
                registry: https://ghcr.io
                username: ${{ secrets.GH_ACTOR }}
                password: ${{ secrets.GH_TOKEN }}

        - 
            name: Build and push Docker image
            uses: docker/build-push-action@v5
            with:
                context: ./Backend
                push: true
                tags: ghcr.io/Bruol/elect-o-mate-backend:latest

        -
            name: Build and push
            uses: docker/build-push-action@v5
            with:
                context: ./Backend
                push: true
                platforms: linux/amd64,linux/arm64
                tags: bruol0/elect-o-mate-backend:latest

    build-frontend:
        runs-on: ubuntu-latest
        steps:
        -
            name: Checkout
            uses: actions/checkout@v4
        -
            name: Set up QEMU
            uses: docker/setup-qemu-action@v3
        -
            name: Set up Docker Buildx
            uses: docker/setup-buildx-action@v3
        -
            name: Login to Docker Hub
            uses: docker/login-action@v3
            with:
                username: ${{ secrets.DOCKERHUB_USERNAME }}
                password: ${{ secrets.DOCKERHUB_TOKEN }}
        -
            name: Build and push
            uses: docker/build-push-action@v5
            with:
                context: ./Frontend/elect-o-mate
                push: true
                platforms: linux/amd64,linux/arm64
                tags: bruol0/elect-o-mate-frontend:latest